title: "Bee Planet Connection"
description: "Connecting people, bees and knowledge."
url: "https://www.beeplanetconnection.org"
baseurl: ""

markdown: kramdown
theme: null

permalink: /:name.html

collections:
  wiki:
    output: true
    permalink: /wiki/:name.html

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

# Keep assets public; exclude build-only or tmp files if needed
exclude:
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "wiki"
      type: "wiki"
    values:
      layout: default

# If you use Google Analytics, set here (optional)
# google_analytics: "G-XXXXXXXXXX"
