baseURL = "https://www.beeplanetconnection.org/"
languageCode = "en-gb"
title = "Bee Planet Connection"

[[menu.main]]
name  = "Wiki"
url   = "/wiki/"
weight = 10

[taxonomies]
  topic = "topics"
  audience = "audiences"
[[menu.main]]
name = "Topics"
url  = "/topics/"
weight = 15

[[menu.main]]
name = "Audiences"
url  = "/audiences/"
weight = 16
