name: Build News Blog
on:
  schedule:
    - cron: "17 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser html5lib lxml requests python-dateutil
      - name: Build news
        run: |
          python scripts/build_news.py
      - name: Commit changes
        run: |
          git config user.name "beeplanet-newsbot"
          git config user.email "newsbot@users.noreply.github.com"
          git add blog/posts/*.md blog/posts/index.json blog/posts/schema.jsonld blog/feed.xml || true
          git commit -m "news: update feed" || echo "Nothing to commit"
          git push
