baseURL = "https://YOUR-USERNAME.github.io/"
languageCode = "en-us"
title = "Bee Planet Connection"
paginate = 10

# keep Hugo from touching quarantined or raw files if you add them later
ignoreFiles = [
  '^assets/_scss_off/.*',
  '^raw/.*\\.csv$'
]

[taxonomies]
tag = "tags"
category = "categories"

[params]
# you can change this later; if present, it’ll be used on the home page hero
homeHero = "/img/hero/home-md.jpg"
