baseURL = "https://www.beeplanetconnection.org/"
title = "Bee Planet Connection"
enableGitInfo = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/blog/:slug/"
  wiki = "/wiki/:sections[1:]/:slug/"
  sops = "/sops/:slug/"
  alerts = "/alerts/:year/:slug/"

[params]
  heroDefaultID = "03"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
