name: Guard: No Generated HTML in Git

on:
  pull_request:
    branches: [ "main" ]

jobs:
  no-generated-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: List changed files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD > changed_files.txt
          echo "Changed files:"; cat changed_files.txt

      - name: Fail if generated HTML under public/ or docs/ is committed
        run: |
          if grep -E '^(public|docs)/.*\.html$' changed_files.txt; then
            echo "::error::Built HTML under public/ or docs/ was committed. HTML must only be produced in CI."
            exit 1
          fi
          echo "No generated HTML files were committed ✅"
