name: Link Check

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'  # daily at 06:00 UTC

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run link checker (lychee)
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          args: >
            --verbose
            --no-progress
            --max-redirects 5
            --exclude-mail
            --cache
            --accept 200,206,301,302,303,307,308
            .
            ./sitemap.xml
          fail: true

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: ./lychee*.json
