name: Build and Link Check

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.134.3"
          extended: true

      - name: Build site
        run: hugo -s site -d ../docs --baseURL "/"

      - name: Lychee link check
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --config .lychee.toml
            --verbose
            docs/**/*.html
            docs/sitemap.xml
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
