name: Build & Link Check

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.134.3'
          extended: true

      - name: Build site (use config baseURL)
        run: |
          hugo -s site -d ../docs

      - name: Lychee Link Check
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --no-progress --verbose
            --config .lychee.toml
            docs/**/*.html docs/sitemap.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
